// frontend/lib/contracts/addresses.ts
/**
 * Contract address registry for Esmond on Paseo testnet.
 * Source of truth: deployments/paseo/addresses.json (generated by AGT-03)
 *
 * At build time, Next.js inlines these via environment variables.
 * All values must be present in .env.local for local dev.
 */

// Chain ID: 420420417 (Paseo Asset Hub — confirmed on-chain by AGT-03/AGT-04)
export const CHAIN_ID = 420420417 as const;

// ─── Precompile Addresses ──────────────────────────────────────────────────
// These are FIXED — they never change regardless of deployment
// Formula: 0xFFFFFFFF + 12×0x00 + assetId(4 bytes BE)
export const PRECOMPILES = {
  XCM:       "0x00000000000000000000000000000000000A0000" as `0x${string}`,
  MOCK_USDC: "0xFFFFFFFF000000000000000000000000000007C0"  as `0x${string}`, // assetId 1984
  MOCK_USDT: "0xFFFFFFFF00000000000000000000000000000539"  as `0x${string}`, // assetId 1337
} as const;

// ─── Asset IDs (for PAPI substrate-level queries) ─────────────────────────
export const ASSET_IDS = {
  MOCK_USDC: 1984,
  MOCK_USDT: 1337,
} as const;

// ─── Deployed Contract Addresses ─────────────────────────────────────────
// These are loaded from environment variables set at build time.
// Populate .env.local with values from deployments/paseo/addresses.json
function requireEnv(key: string): `0x${string}` {
  const val = process.env[key];
  if (!val) throw new Error(`Missing env var: ${key}. Add it to .env.local from deployments/paseo/addresses.json`);
  return val as `0x${string}`;
}

export function getContractAddresses() {
  return {
    PayrollVault:        requireEnv("NEXT_PUBLIC_PAYROLL_VAULT_ADDRESS"),
    ConditionalEscrow:   requireEnv("NEXT_PUBLIC_CONDITIONAL_ESCROW_ADDRESS"),
    SubscriptionManager: requireEnv("NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS"),
    ActiveScheduler:     requireEnv("NEXT_PUBLIC_ACTIVE_SCHEDULER_ADDRESS"),
  } as const;
}

// ─── Supported Tokens ────────────────────────────────────────────────────
export type SupportedToken = "mUSDC" | "mUSDT";

export const TOKEN_CONFIG: Record<SupportedToken, {
  address:  `0x${string}`;
  assetId:  number;
  decimals: number;
  symbol:   string;
}> = {
  mUSDC: { address: PRECOMPILES.MOCK_USDC, assetId: ASSET_IDS.MOCK_USDC, decimals: 6, symbol: "mUSDC" },
  mUSDT: { address: PRECOMPILES.MOCK_USDT, assetId: ASSET_IDS.MOCK_USDT, decimals: 6, symbol: "mUSDT" },
};

// ─── Test Token (MockERC20) ───────────────────────────────────────────────
// Deployed by AGT-07 to unblock integration tests (asset-1984 precompile has
// zero supply — 3rd-party admin). Components use this for all write-path calls.
// Falls back to PRECOMPILES.MOCK_USDC if env var is absent.
export const MOCK_ERC20_ADDRESS = (
  process.env.NEXT_PUBLIC_MOCK_ERC20_ADDRESS ?? PRECOMPILES.MOCK_USDC
) as `0x${string}`;

// ─── Parachain IDs ───────────────────────────────────────────────────────
export const PARACHAIN_IDS = {
  HUB:       0,
  MOONBEAM:  2004,
  ASTAR:     2006,
  HYDRATION: 2034,
} as const;

export type ParachainId = typeof PARACHAIN_IDS[keyof typeof PARACHAIN_IDS];

export const PARACHAIN_NAMES: Record<ParachainId, string> = {
  0:    "Polkadot Hub",
  2004: "Moonbeam",
  2006: "Astar",
  2034: "Hydration",
};
